insert into fields (id, name, default_value, alias, enabled, "order") values (1, 'TaskNumber', 'Task ID', 'Task ID', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (2, 'TaskDescription', 'Task Description', 'Task Description', true, 2);
insert into fields (id, name, default_value, alias, enabled, "order") values (3, 'TaskTargetStart', 'Target Start', 'Target Start', true, 3);
insert into fields (id, name, default_value, alias, enabled, "order") values (4, 'TaskDuration', 'Duration', 'Duration', true, 4);
insert into fields (id, name, default_value, alias, enabled, "order") values (5, 'TaskTargetFinish', 'Target Finish', 'Target Finish', true, 5);
insert into fields (id, name, default_value, alias, enabled, "order") values (6, 'TaskActualFinish', 'Actual Finish', 'Actual Finish', false, 6);
insert into fields (id, name, default_value, alias, enabled, "order") values (7, 'TaskOrder', 'Task #', 'Task #', false, 7);
insert into fields (id, name, default_value, alias, enabled, "order") values (8, 'TaskStatus', 'Status', 'Status', false, 8);
insert into fields (id, name, default_value, alias, enabled, "order") values (9, 'TaskFollows', 'Follows Task', 'Follows Task', false, 9);
insert into fields (id, name, default_value, alias, enabled, "order") values (10, 'TaskRequested', 'Requested by', 'Requested by', false, 10);
insert into fields (id, name, default_value, alias, enabled, "order") values (11, 'TaskNotes', 'Detailed Task Notes', 'Detailed Task Notes', false, 11);
insert into fields (id, name, default_value, alias, enabled, "order") values (12, 'TaskMarked', 'Marked', 'Marked', false, 12);

insert into fields (id, name, default_value, alias, enabled, "order") values (13, 'JobNumber', 'Job #', 'Job #', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (14, 'JobLot', 'Lot #', 'Lot #', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (15, 'JobSubdivision', 'Subdivision', 'Subdivision', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (16, 'JobOwnerName', 'Owner''s Name', 'Owner''s Name', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (17, 'JobLockBox', 'Lock Box Combo', 'Lock Box Combo', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (18, 'JobDirections', 'Directions to Job Site', 'Directions to Job Site', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (19, 'JobNotes', 'Job Site Notes', 'Job Site Notes', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (20, 'JobAddress1', 'Address', 'Address', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (21, 'JobAddress2', 'Address 2', 'Address 2', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (22, 'JobCity', 'City', 'City', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (23, 'JobState', 'State', 'State', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (24, 'JobPostal', 'Postal', 'Postal', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (25, 'JobHomePhone', 'Owner''s Home#', 'Owner''s Home#', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (26, 'JobWorkPhone', 'Work #', 'Work #', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (27, 'JobCellPhone', 'Cell #', 'Cell #', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (28, 'JobFax', 'Fax number', 'Fax number', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (29, 'JobCompany', 'Company Name', 'Company Name', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (30, 'JobEmail', 'Email', 'Email', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (31, 'JobCountry', 'Country/Region', 'Country/Region', true, 1);

insert into fields (id, name, default_value, alias, enabled, "order") values (32, 'ContactCompany', 'Company', 'Company', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (33, 'ContactProfession', 'Profession', 'Profession', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (34, 'ContactPerson', 'Person''s Name', 'Person''s Name', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (35, 'ContactLastName', 'Last Name', 'Last Name', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (36, 'ContactFirstName', 'First', 'First', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (37, 'ContactSupervisor', 'Supervisor', 'Supervisor', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (38, 'ContactSpouse', 'Spouse', 'Spouse', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (39, 'ContactTaxID', 'Tax ID', 'Tax ID', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (40, 'ContactWebSite', 'Web Site', 'Web Site', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (41, 'ContactWorkersCompDate', 'Workers Comp good through', 'Workers Comp good through', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (42, 'ContactInsuranceDate', 'Insurance good through', 'Insurance good through', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (43, 'ContactComments', 'Comments', 'Comments', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (44, 'ContactNotes', 'Notes', 'Notes', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (45, 'ContactFax', 'Fax #', 'Fax #', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (46, 'ContactEmail', 'EMail Address', 'EMail Address', true, 1);
insert into fields (id, name, default_value, alias, enabled, "order") values (47, 'ContactPhones', 'Contact phone #s', 'Contact phone #s', true, 1);