spring:
  application:
    name: virtualboss
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/virtualboss}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 300000
#      pool-name: HikariCP
#      max-lifetime: 600000

  codec:
    max-in-memory-size: 1048576
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  liquibase:
    change-log: classpath://db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: never

  mandatory-file-encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  config:
    import:
      - migration-config.yml

 # Logging settings
logging:
  level:
      com:
        zaxxer:
          hikari:
            TRACE:
            HikariConfig:
              DEBUG

server:
  port: 8080
  servlet:
    context-path: /api/v1
