spring:
  application:
    name: virtualboss
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://virtualbosspgserver.postgres.database.azure.com:5432/virtualboss?sslmode=require}
    username: ${DATABASE_USER:pgadmin}
    password: ${DATABASE_PASSWORD:${pguser-password}}
    driver-class-name: org.postgresql.Driver

#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 300000
#      pool-name: HikariCP
#      max-lifetime: 600000

  codec:
    max-in-memory-size: 1048576
  data:
    redis:
      host: ${REDIS_HOST:virtualbossredis.redis.cache.windows.net}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:${redis-password}}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}

  jpa:
    hibernate:
        ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath://db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: never

  mandatory-file-encoding: UTF-8

  config:
    import:
      - migration-config.yml

  cloud:
    azure:
      keyvault:
        secret:
          enabled: true
          endpoint: https://virtualboss-keyvault.vault.azure.net/

 # Logging settings
logging:
  level:
      com:
        zaxxer:
          hikari:
            TRACE:
            HikariConfig:
              DEBUG

server:
  port: 8080
  servlet:
    context-path: /api/v1

file:
  upload:
    path: ${FILE_UPLOAD_PATH:classpath:temp/}
migration:
  test-data-path: "classpath:testdata"
