spring:
  application:
    name: virtualBoss
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/virtualboss}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath://db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: never

  mandatory-file-encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /api/v1

