services:
  postgres:
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=virtualboss
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      virtualbossnet:
#        aliases:
#          - postgres
#    deploy:
#      placement:
#        constraints:
#          - node.labels.type == postgres
#          - node.hostname == postgres
#          - node.role == worker
#    cap_add:
#      - NET_RAW
#      - NET_ADMIN
#      - NET_BROADCAST
#      - NET_BIND_SERVICE

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1

#  virtualboss:
#    hostname: 'virtualboss'
#    image: ragaev/virtualboss:0.0.1-SNAPSHOT
#    environment:
#      - DATABASE_URL=jdbc:postgresql://postgres:5432/virtualboss
#    ports:
#      - "8080:8080"
#    restart: on-failure
#    networks:
#      virtualbossnet:
#    deploy:
#      placement:
#        constraints:
#          - node.labels.type != postgres
#          - node.role == worker

  frontend:
    image: ragaev/frontend:virtualboss
    ports:
      - "80:80"
    tty: true
    restart: on-failure
    volumes:
      - ./nginx-config.local:/etc/nginx/conf.d
    networks:
      virtualbossnet:
    deploy:
      placement:
        constraints:
          - node.labels.type != postgres
          - node.role == worker

volumes:
  pgdata:
networks:
  virtualbossnet:
#    driver: overlay
#    driver_opts:
#      com.docker.network.driver.mtu: 1450
